### ISSUE TITLE
Post creation error

### ISSUE THREAD

**Issue by Venirails** [MilesUpHQ/reddit-clone-rails#33]
When I try to create a new post, either publish or save as draft this error is occurring 

<img width="1265" alt="Screenshot 2022-12-28 at 3 28 09 PM" src="https://user-images.githubusercontent.com/7172445/209794596-1d1880a1-3495-47b9-8a01-b0ae02965f1f.png">

I checked with Aboorva. She is also getting the same error.

**Comment by ksowndar** [comment]
1. It is now corrected.
2. Now we can able to publish the post and drafts issue also solved.
3. https://github.com/MilesUpHQ/reddit-clone-rails/pull/42

**Comment by iMagesh** [comment]
This error still exists when i miss to fill a field. Can you test well and fix it? @ksowndar

**Comment by ksowndar** [comment]
It is fixed now @iMagesh , Verify it.
![image](https://user-images.githubusercontent.com/84360457/210938243-2c4672e9-e992-428a-8b51-2cf69fd5e554.png)
